const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let file=null,registerMode=false,token=localStorage.getItem('cv_token')||'';
const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`,esc=v=>{const n=document.createElement('span');n.textContent=String(v??'');return n.innerHTML};
async function api(path,options={}){const headers=new Headers(options.headers||{});if(token)headers.set('Authorization',`Bearer ${token}`);if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');const r=await fetch(path,{...options,headers});if(r.status===401&&token){logout();throw Error('Your session expired. Please sign in again.')}if(!r.ok){let m=`Request failed (${r.status})`;try{m=(await r.json()).detail||m}catch{}throw Error(m)}return r.json()}
function showApp(user){$('#authScreen').classList.add('hidden');$('#userEmail').textContent=user.email}
function logout(){token='';localStorage.removeItem('cv_token');$('#authScreen').classList.remove('hidden');$('#userEmail').textContent=''}
async function restoreSession(){if(!token)return;try{showApp(await api('/api/v1/auth/me'))}catch{logout()}}
async function authenticate(e){e.preventDefault();const b=$('#authSubmit');b.disabled=true;$('#authError').textContent='';try{const d=await api(`/api/v1/auth/${registerMode?'register':'login'}`,{method:'POST',body:JSON.stringify({email:$('#authEmail').value,password:$('#authPassword').value})});token=d.access_token;localStorage.setItem('cv_token',token);showApp(d.user);health()}catch(x){$('#authError').textContent=x.message}finally{b.disabled=false}}
function toggleAuth(){registerMode=!registerMode;$('#authTitle').textContent=registerMode?'Create account.':'Welcome back.';$('#authSubtitle').textContent=registerMode?'Register to keep your predictions private.':'Sign in to access your private prediction workspace.';$('#authSubmit span').textContent=registerMode?'Create account':'Sign in';$('#authToggle').textContent=registerMode?'Already registered? Sign in':'Create a new account';$('#authPassword').autocomplete=registerMode?'new-password':'current-password';$('#authError').textContent=''}
async function health(){const s=$('.system-status');try{const d=await api('/health'),ok=d.api==='healthy'&&d.database==='healthy'&&d.model==='loaded';s.className=`system-status ${ok?'online':'offline'}`;$('#statusText').textContent=ok?'All systems operational':'System degraded'}catch{s.className='system-status offline';$('#statusText').textContent='Backend offline'}}
function clearFile(){file=null;$('#imageInput').value='';$('#preview').removeAttribute('src');$('#dropZone').classList.remove('has-image');$('#fileMeta').textContent='';$('#classifyButton').disabled=true}
function choose(f){$('#errorMessage').textContent='';if(!f)return clearFile();if(!['image/jpeg','image/png','image/webp'].includes(f.type))return $('#errorMessage').textContent='Please select a PNG, JPG, or WEBP image.';if(f.size>10485760)return $('#errorMessage').textContent='Image exceeds the 10 MB upload limit.';file=f;$('#preview').src=URL.createObjectURL(f);$('#dropZone').classList.add('has-image');$('#classifyButton').disabled=false;$('#fileMeta').textContent=`${f.name.toUpperCase()} · ${(f.size/1048576).toFixed(2)} MB`}
async function classify(){if(!file)return;const b=$('#classifyButton');b.disabled=true;$('#errorMessage').textContent='';const form=new FormData();form.append('image',file);try{render(await api('/api/v1/predict',{method:'POST',body:form}))}catch(e){$('#errorMessage').textContent=e.message}finally{b.disabled=false}}
function render(d){$('#resultPanel').classList.add('has-result');$('#resultClass').textContent=d.predicted_class.replaceAll('_',' ');$('#resultConfidence').textContent=pct(d.confidence);$('#confidenceRing').style.background=`conic-gradient(var(--green) ${Number(d.confidence)*360}deg,#233229 0deg)`;$('#inferenceTime').textContent=`${Number(d.inference_ms).toFixed(2)} MS`;$('#recordId').textContent=`#${String(d.id).padStart(4,'0')}`;$('#modelVersion').textContent=`MODEL V${d.model_version}`;$('#topPredictions').innerHTML=(d.top_k_predictions||d.top_predictions||[]).map(x=>`<div class="rank-row"><span>${esc(x.class_name.replaceAll('_',' '))}</span><div class="rank-track"><div class="rank-fill" style="width:${Number(x.probability)*100}%"></div></div><span class="rank-value">${pct(x.probability)}</span></div>`).join('')}
async function history(){const b=$('#historyBody'),e=$('#historyEmpty');b.innerHTML='<tr><td colspan="6">Loading mission archive…</td></tr>';e.style.display='none';try{const rows=await api('/api/v1/predictions?limit=50');b.innerHTML=rows.map(r=>`<tr><td>#${r.id}</td><td>${esc(r.image_name)}</td><td class="class-chip">${esc(r.predicted_class.replaceAll('_',' '))}</td><td>${pct(r.confidence)}</td><td>${Number(r.inference_ms).toFixed(2)} ms</td><td>${new Date(r.created_at).toLocaleString()}</td></tr>`).join('');if(!rows.length)e.style.display='block'}catch(x){b.innerHTML=`<tr><td colspan="6">${esc(x.message)}</td></tr>`}}
async function dashboard(){try{const[s,m,o]=await Promise.all([api('/api/v1/stats'),api('/api/v1/model'),api('/api/v1/monitoring')]);$('#totalPredictions').textContent=s.total_predictions.toLocaleString();$('#averageConfidence').textContent=s.average_confidence==null?'—':pct(s.average_confidence);$('#averageInference').textContent=s.average_inference_ms==null?'—':`${Number(s.average_inference_ms).toFixed(1)} ms`;$('#recentPredictions').textContent=o.predictions_last_24h;$('#lowConfidence').textContent=o.low_confidence_rate==null?'—':pct(o.low_confidence_rate);$('#versionCount').textContent=Object.keys(o.model_versions).length;const max=Math.max(1,...Object.values(s.class_distribution));$('#distributionChart').innerHTML=Object.entries(s.class_distribution).map(([n,c])=>`<div class="dist-row"><span>${esc(n.replaceAll('_',' '))}</span><div class="dist-track"><div class="dist-fill" style="width:${c/max*100}%"></div></div><strong class="dist-count">${c}</strong></div>`).join('')||'<p class="table-empty" style="display:block">No classification data yet.</p>';$('#modelDetails').innerHTML=`<div class="detail-row"><span>Architecture</span><strong>${esc(m.model_name)}</strong></div><div class="detail-row"><span>Version</span><strong>v${esc(m.model_version)}</strong></div><div class="detail-row"><span>Input resolution</span><strong>${m.input_size.join(' × ')} px</strong></div><div class="detail-row"><span>Deployment status</span><strong>${esc(m.status.toUpperCase())}</strong></div><div class="model-classes">${m.classes.map(c=>`<i>${esc(c.replaceAll('_',' '))}</i>`).join('')}</div>`}catch(e){$('#distributionChart').innerHTML=`<p class="error-message">${esc(e.message)}</p>`}}
function addMessage(text,kind){const m=document.createElement('div');m.className=`chat-message ${kind}-message`;m.textContent=text;$('#chatMessages').appendChild(m);m.scrollIntoView({behavior:'smooth',block:'nearest'})}
function speak(text){if(!('speechSynthesis'in window))return false;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=/[\u0600-\u06ff]/.test(text)?'ar-SA':'en-US';window.speechSynthesis.speak(u);return true}
async function askAgent(e){e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;input.value='';addMessage(text,'user');$('#sendButton').disabled=true;$('#voiceStatus').textContent='Agent is using application tools…';try{const d=await api('/agent/v1/chat/completions',{method:'POST',body:JSON.stringify({model:'satellite-cv-agent',messages:[{role:'user',content:text}],stream:false})});const answer=d.choices?.[0]?.message?.content||'No response returned.';addMessage(answer,'agent');$('#voiceStatus').textContent=speak(answer)?'Response received and spoken aloud.':'Response received. Voice output is unavailable in this browser.'}catch(x){addMessage(x.message,'error');$('#voiceStatus').textContent='Agent request failed.'}finally{$(`#sendButton`).disabled=false}}
function startVoice(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('#voiceStatus').textContent='Speech recognition is not supported in this browser.';return}const r=new Recognition();r.lang=navigator.language||'en-US';r.interimResults=false;r.onstart=()=>{$('#micButton').classList.add('listening');$('#voiceStatus').textContent='Listening…'};r.onresult=e=>{$('#chatInput').value=e.results[0][0].transcript;$('#voiceStatus').textContent='Speech converted to text. Press Send to continue.'};r.onerror=e=>{$('#voiceStatus').textContent=`Microphone error: ${e.error}`};r.onend=()=>$('#micButton').classList.remove('listening');r.start()}
$$('.nav-link').forEach(b=>b.onclick=()=>{$$('.nav-link,.view').forEach(e=>e.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active');if(b.dataset.view==='history')history();if(b.dataset.view==='dashboard')dashboard();scrollTo({top:0,behavior:'smooth'})});
$('#authForm').onsubmit=authenticate;$('#authToggle').onclick=toggleAuth;$('#logoutButton').onclick=logout;$('#chatForm').onsubmit=askAgent;$('#micButton').onclick=startVoice;$('#imageInput').onchange=e=>choose(e.target.files[0]);$('#removeImage').onclick=e=>{e.preventDefault();clearFile()};$('#classifyButton').onclick=classify;['dragenter','dragover'].forEach(n=>$('#dropZone').addEventListener(n,e=>{e.preventDefault();$('#dropZone').classList.add('dragging')}));['dragleave','drop'].forEach(n=>$('#dropZone').addEventListener(n,e=>{e.preventDefault();$('#dropZone').classList.remove('dragging')}));$('#dropZone').ondrop=e=>choose(e.dataTransfer.files[0]);$$('[data-refresh]').forEach(b=>b.onclick=()=>b.dataset.refresh==='history'?history():dashboard());restoreSession();health();setInterval(health,30000);
